/**
 * The demo account.
 *
 * A fictional recent graduate with a biweekly paycheck, a fixed set of monthly
 * bills, irregular grocery and coffee spending, a small monthly transfer from
 * family, and a couple of one-off purchases.
 *
 * The dataset is generated RELATIVE TO TODAY (about 95 days of history ending
 * yesterday) so the demo never expires. It is ordinary transaction data: it
 * carries no predictions, no labels and no expected results. Everything the
 * forecast screen shows is derived by the same detection and forecast code that
 * runs on an uploaded CSV — nothing about the demo is hard-coded downstream.
 *
 * Recurring bills are anchored by HOW MANY DAYS UNTIL THEIR NEXT OCCURRENCE
 * rather than by a fixed day of the month, and the paycheck is anchored so the
 * next payday is 13 days out. That keeps the demonstration stable: whatever day
 * the demo is opened, the same obligations fall between today and payday, so
 * the projected low point is the same story every time.
 *
 * The amounts and offsets are the only thing tuned here. The forecast itself is
 * whatever the detectors and the forecast engine make of this history.
 */

import type { Transaction } from '../domain/types'
import { addDays, addMonthsClamped } from '../domain/dateUtils'

/** The demo user's checking balance on the as-of date. */
export const DEMO_STARTING_BALANCE = 2140.0

/** Days of history the demo generates. */
const DEMO_HISTORY_DAYS = 95

interface OneOffCharge {
  /** Days before the as-of date. */
  daysAgo: number
  merchant: string
  amount: number
  category: string
}

interface MonthlyCharge {
  /**
   * Days from the as-of date to this bill's next occurrence. History is
   * generated by stepping back whole months from that anchor, so the detector
   * sees a clean monthly cadence and projects the next date back onto it.
   *
   * Values below PAYDAY_IN_DAYS fall inside the pre-payday window and shape the
   * projected low point; values above it are found by the detector but sit
   * beyond the forecast horizon.
   */
  daysUntilNext: number
  merchant: string
  /** Oldest first. The median becomes the predicted amount. */
  amounts: number[]
  category: string
}

/** How many historical occurrences each monthly bill gets. */
const MONTHLY_HISTORY_COUNT = 3

/**
 * Fixed obligations.
 *
 * The five inside the pre-payday window are the ones a student or recent
 * graduate actually feels: rent, the card payment, the phone bill, the gym and
 * the student loan. Together they take the demo balance from $2,140 down to a
 * low in the $500s before the paycheck arrives — which is the point the product
 * exists to make visible.
 */
const MONTHLY_CHARGES: MonthlyCharge[] = [
  {
    daysUntilNext: 4,
    merchant: 'CEDAR RIDGE APTS RENT',
    amounts: [-1150.0],
    category: 'Housing',
  },
  {
    daysUntilNext: 6,
    merchant: 'CHASE CARD PAYMENT 4421',
    amounts: [-252.4, -259.99, -266.15],
    category: 'Credit card',
  },
  {
    daysUntilNext: 8,
    merchant: 'PLANET FITNESS #2231',
    amounts: [-24.99],
    category: 'Health',
  },
  {
    daysUntilNext: 10,
    merchant: 'MINT MOBILE 8887890',
    amounts: [-30.0],
    category: 'Utilities',
  },
  {
    daysUntilNext: 12,
    merchant: 'NELNET STUDENT LOAN',
    amounts: [-145.0],
    category: 'Loans',
  },
  // Beyond the next payday: detected, but outside the forecast horizon.
  {
    daysUntilNext: 16,
    merchant: 'XFINITY INTERNET 8009345',
    amounts: [-64.99],
    category: 'Utilities',
  },
  {
    daysUntilNext: 18,
    merchant: 'SPOTIFY USA 877-778-1161',
    amounts: [-11.99],
    category: 'Subscriptions',
  },
  {
    daysUntilNext: 20,
    merchant: 'ZELLE FROM PARENT',
    amounts: [200.0],
    category: 'Transfer',
  },
]

/**
 * Irregular spending. None of this should be predicted: the gaps are weekly or
 * fortnightly rather than monthly, or the merchant appears only once.
 */
const ONE_OFF_CHARGES: OneOffCharge[] = [
  // Groceries — roughly every two weeks per store, amounts all over the place.
  { daysAgo: 88, merchant: "TRADER JOE'S #455", amount: -62.18, category: 'Groceries' },
  { daysAgo: 74, merchant: "TRADER JOE'S #455", amount: -48.9, category: 'Groceries' },
  { daysAgo: 61, merchant: "TRADER JOE'S  #455", amount: -71.44, category: 'Groceries' },
  { daysAgo: 47, merchant: "TRADER JOE'S #455", amount: -55.2, category: 'Groceries' },
  { daysAgo: 33, merchant: "TRADER JOE'S #455", amount: -83.11, category: 'Groceries' },
  { daysAgo: 19, merchant: "TRADER JOE'S #455", amount: -44.75, category: 'Groceries' },
  { daysAgo: 6, merchant: "TRADER JOE'S #455", amount: -67.32, category: 'Groceries' },
  { daysAgo: 81, merchant: 'SAFEWAY 1123', amount: -34.12, category: 'Groceries' },
  { daysAgo: 68, merchant: 'SAFEWAY 1123', amount: -52.66, category: 'Groceries' },
  { daysAgo: 54, merchant: 'SAFEWAY 1123', amount: -29.9, category: 'Groceries' },
  { daysAgo: 40, merchant: 'SAFEWAY 1123', amount: -61.4, category: 'Groceries' },
  { daysAgo: 26, merchant: 'SAFEWAY 1123', amount: -38.75, category: 'Groceries' },
  { daysAgo: 12, merchant: 'SAFEWAY 1123', amount: -47.2, category: 'Groceries' },

  // Coffee — weekly-ish, small, never monthly.
  { daysAgo: 86, merchant: 'STARBUCKS 00291', amount: -6.45, category: 'Dining' },
  { daysAgo: 79, merchant: 'STARBUCKS 00291', amount: -5.1, category: 'Dining' },
  { daysAgo: 72, merchant: 'STARBUCKS 00291', amount: -7.8, category: 'Dining' },
  { daysAgo: 66, merchant: 'STARBUCKS 00291', amount: -4.95, category: 'Dining' },
  { daysAgo: 59, merchant: 'STARBUCKS 00291', amount: -6.45, category: 'Dining' },
  { daysAgo: 51, merchant: 'STARBUCKS 00291', amount: -8.2, category: 'Dining' },
  { daysAgo: 44, merchant: 'STARBUCKS 00291', amount: -5.6, category: 'Dining' },
  { daysAgo: 37, merchant: 'STARBUCKS 00291', amount: -6.45, category: 'Dining' },
  { daysAgo: 29, merchant: 'STARBUCKS 00291', amount: -7.15, category: 'Dining' },
  { daysAgo: 22, merchant: 'STARBUCKS 00291', amount: -5.1, category: 'Dining' },
  { daysAgo: 15, merchant: 'STARBUCKS 00291', amount: -6.9, category: 'Dining' },
  { daysAgo: 8, merchant: 'STARBUCKS 00291', amount: -6.45, category: 'Dining' },
  { daysAgo: 3, merchant: 'STARBUCKS 00291', amount: -4.75, category: 'Dining' },

  // Delivery and rides — irregular gaps.
  { daysAgo: 83, merchant: 'DOORDASH*THAI GARDEN', amount: -28.4, category: 'Dining' },
  { daysAgo: 70, merchant: 'DOORDASH*SUSHI HOUSE', amount: -41.15, category: 'Dining' },
  { daysAgo: 57, merchant: 'DOORDASH*THAI GARDEN', amount: -22.9, category: 'Dining' },
  { daysAgo: 41, merchant: 'DOORDASH*BURGER CO', amount: -33.7, category: 'Dining' },
  { daysAgo: 24, merchant: 'DOORDASH*THAI GARDEN', amount: -26.85, category: 'Dining' },
  { daysAgo: 10, merchant: 'DOORDASH*SUSHI HOUSE', amount: -38.2, category: 'Dining' },
  { daysAgo: 77, merchant: 'UBER *TRIP 8842', amount: -18.6, category: 'Transport' },
  { daysAgo: 58, merchant: 'UBER *TRIP 1190', amount: -24.35, category: 'Transport' },
  { daysAgo: 31, merchant: 'UBER *TRIP 4471', amount: -12.8, category: 'Transport' },
  { daysAgo: 9, merchant: 'UBER *TRIP 6620', amount: -31.05, category: 'Transport' },
  { daysAgo: 76, merchant: 'CHIPOTLE 2284', amount: -14.25, category: 'Dining' },
  { daysAgo: 52, merchant: 'CHIPOTLE 2284', amount: -16.8, category: 'Dining' },
  { daysAgo: 21, merchant: 'CHIPOTLE 2284', amount: -13.4, category: 'Dining' },

  // One-off merchants that appear exactly once.
  { daysAgo: 63, merchant: 'CAMPUS BOOKSTORE', amount: -87.4, category: 'Education' },
  { daysAgo: 45, merchant: 'VENMO PAYMENT TO MAYA', amount: -35.0, category: 'Transfer' },
  { daysAgo: 35, merchant: 'REI ADVENTURE OUTFITTERS #88', amount: -142.37, category: 'Shopping' },
  { daysAgo: 17, merchant: 'CVS PHARMACY 7712', amount: -23.18, category: 'Health' },
]

/** Biweekly paycheck. Net pay moves a little with hours, well inside the 20% band. */
const PAYROLL_MERCHANT = 'NORTHGATE UNIV PAYROLL'
const PAYROLL_AMOUNTS = [1412.55, 1398.2, 1421.08, 1412.55, 1405.6, 1412.55, 1398.2]

/** Days between paydays, and how long ago the most recent one landed. */
const PAYROLL_INTERVAL_DAYS = 14
const DAYS_SINCE_LAST_PAYDAY = 1

/**
 * Days from the as-of date to the next paycheck, and therefore to the end of
 * the forecast window. Every bill above with a smaller offset lands before it.
 */
export const PAYDAY_IN_DAYS = PAYROLL_INTERVAL_DAYS - DAYS_SINCE_LAST_PAYDAY

export interface DemoDataset {
  transactions: Transaction[]
  currentBalance: number
  asOfDate: string
  /** First date covered by the generated history. */
  historyStartDate: string
}

/**
 * The historical occurrences of a monthly bill, oldest first.
 *
 * Stepping back whole calendar months from the next-occurrence anchor keeps the
 * day of the month stable, which is how real billers behave. Month-end clamping
 * can pull the projected next date a day or two earlier than the anchor, never
 * later, so a bill anchored inside the window stays inside it.
 */
function monthlyHistory(anchorDate: string, count: number): string[] {
  const dates: string[] = []
  for (let monthsBack = count; monthsBack >= 1; monthsBack -= 1) {
    dates.push(addMonthsClamped(anchorDate, -monthsBack))
  }
  return dates
}

/**
 * Build the demo account as of `asOfDate` (defaults to today).
 *
 * The output is plain transaction history. Run it through the same detectors
 * and forecast engine as any uploaded file to see the projection.
 */
export function buildDemoDataset(asOfDate: string): DemoDataset {
  const historyStartDate = addDays(asOfDate, -DEMO_HISTORY_DAYS)
  const lastHistoryDate = addDays(asOfDate, -1)
  const rows: Omit<Transaction, 'id'>[] = []

  // Paychecks, walking backwards from the most recent one.
  let payday = addDays(asOfDate, -DAYS_SINCE_LAST_PAYDAY)
  for (let index = 0; payday >= historyStartDate; index += 1) {
    rows.push({
      date: payday,
      merchant: PAYROLL_MERCHANT,
      amount: PAYROLL_AMOUNTS[index % PAYROLL_AMOUNTS.length],
      category: 'Income',
    })
    payday = addDays(payday, -PAYROLL_INTERVAL_DAYS)
  }

  // Fixed monthly bills and the monthly transfer.
  for (const charge of MONTHLY_CHARGES) {
    const anchor = addDays(asOfDate, charge.daysUntilNext)
    monthlyHistory(anchor, MONTHLY_HISTORY_COUNT).forEach((date, index) => {
      rows.push({
        date,
        merchant: charge.merchant,
        amount: charge.amounts[index % charge.amounts.length],
        category: charge.category,
      })
    })
  }

  // Everyday and one-off spending.
  for (const charge of ONE_OFF_CHARGES) {
    rows.push({
      date: addDays(asOfDate, -charge.daysAgo),
      merchant: charge.merchant,
      amount: charge.amount,
      category: charge.category,
    })
  }

  const sorted = rows
    .filter((row) => row.date >= historyStartDate && row.date <= lastHistoryDate)
    .sort((a, b) =>
      a.date === b.date
        ? a.merchant.localeCompare(b.merchant)
        : a.date < b.date
          ? -1
          : 1,
    )

  return {
    transactions: sorted.map((row, index) => ({ ...row, id: `demo-${index + 1}` })),
    currentBalance: DEMO_STARTING_BALANCE,
    asOfDate,
    historyStartDate,
  }
}
